[package]
name = "named-pipe-to-tcp-proxy"
version = "1.1.1"
edition = "2021"
license = "BSD-3-Clause"
keywords = ["cli", "named-pipes", "windows"]
repository = "https://github.com/FoxxMD/named-pipe-to-tcp-proxy"
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
description = "Proxy all data from a Named Pipe to a specified TCP Proxy Server"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1", features = ["net", "macros", "rt", "io-util"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1